# Hardware --------------------

keyboard_event: "/dev/input/event0"
screen_offset:
  x: 1920
  y: 0

# Key press data --------------

# WRITE THESE AS SECONDS! They will get converted to milliseconds.

# My shortest was 54 ms, fastest was 141 ms.
# My standard deviation was 21 ms.
# For my target, I used my Q3, 110 ms.
key_press:
  shortest: 54
  longest: 141
  range: 5
  std_dev: 21
  target: 110
  test:
    enable: True
    delay: 3
    count: 20

# Flasks ----------------------
flask1:
  enable: True

# Testing ---------------------
image_test:
  enable: False
  save_location: "/home/lemon/Documents/GitHub/poepyautopot/tests/images/"

